number = {
                        1:'one',
                        2:'two',
                        3:'thee',
                        4:'four',
                        5:'five',
                        6:'six',
                        7:'seven',
                        8:'eight',
                        9:'nine',
                        10:',tan',
                        11:'eleven',
                        12:'tleven',
                        13:'thirteen',
                        14:'fourteen',
                        15:'fifteen',
                        16:'sixteen',
                        17:'seventeen',
                        18:'eighteen',
                        19:'ninetten',
                        20:'twenty',
                        21:'twent-one',
                        22:'twent-two',
                        23:'twent-hee',
                        24:'twent-four',
                        25:'twent-five',
                        26:'twent-six',
                        27:'twent-seven',
                        28:'twent-eight',
                        29:'twent-nine',
                        30:'thiry-two',
                        31:'thiry-one',
                        32:'thiry-two',
                        33:'thiry-thee',
                        34:'thiry-four',
                        35:'thiry-five',
                        36:'thiry-six',
                        37:'thiry-seven',
                        38:'thiry-eight',
                        39:'thiry-nine',
                        40:'forty',
                        41:'forty-one',
                        42:'forty-two',
                        43:'forty-thee',
                        44:'forty-four',
                        45:'forty-five',
                        46:'forty-six',
                        47:'forty-seven',
                        48:'forty-eight',
                        49:'forty-nine',
                        50:'fity',
                        51:'fity-one',
                        52:'fity-two',
                        53:'fity-thee',
                        54:'fity-four',
                        55:'fity-five',
                        56:'fity-six',
                        57:'fity-seven',
                        58:'fity-eight',
                        59:'fity-nine',
                        60:'sixty',
                        61:'sixty-one',
                        62:'sixty-two',
                        63:'sixty-thee',
                        64:'sixty-four',
                        65:'sixty-five',
                        66:'sixty-six',
                        67:'sixty-seven',
                        68:'sixty-eight',
                        69:'sixty-nine',
                        70:'seventy',
                        71:'seventy-one',
                        72:'seventy-two',
                        73:'seventy-thee',
                        74:'seventy-four',
                        75:'seventy-five',
                        76:'seventy-six',
                        77:'seventy-seven',
                        78:'seventy-eight',
                        79:'seventy-nine',
                        80:'eighty',
                        81:'eighty-one',
                        82:'eighty-two',
                        83:'eighty-thee',
                        84:'eighty-four',
                        85:'eighty-five',
                        86:'eighty-six',
                        87:'eighty-seven',
                        88:'eighty-eight',
                        89:'eighty-nine',
                        90:'ninety',
                        91:'ninety-one',
                        92:'ninety-two',
                        93:'ninety-thee',
                        94:'ninety-four',
                        95:'ninety-five',
                        96:'ninety-six',
                        97:'ninety-seven',
                        98:'ninety-eight',
                        99:'ninety-nine',
                        100:'one hundred',
                        101:'one hundred one',
                        102:'one hundred two',
                        103:'one hundred thee',
                        104:'one hundred four',
                        105:'one hundred five',
                        106:'one hundred six',
                        107:'one hundred seven',
                        108:'one hundred eight',
                        109:'one hundred nine',
                        110:'one hundred tan',
                        111:'one hundred taneleven',
                        112:'one hundred tantleven',
                        113:'one hundred tanthirteen',
                        114:'one hundred tanfourteen',
                        115:'one hundred tanfifteen',
                        116:'one hundred tansixteen',
                        117:'one hundred tanseventeen',
                        118:'one hundred taneighteen',
                        119:'one hundred tanninetten',
                        120:'one hundred twenty',
                        121:'one hundred twent-one',
                        122:'one hundred twent-two',
                        123:'one hundred twent-hee',
                        124:'one hundred twent-four',
                        125:'one hundred twent-five',
                        126:'one hundred twent-six',
                        127:'one hundred twent-seven',
                        128:'one hundred twent-eight',
                        129:'one hundred twent-nine',
                        130:'one hundred thrity',
                        131:'one hundred thiry-one',
                        132:'one hundred thiry-two',
                        133:'one hundred thiry-thee',
                        134:'one hundred thiry-four',
                        135:'one hundred thiry-five',
                        136:'one hundred thiry-six',
                        137:'one hundred thiry-seven',
                        138:'one hundred thiry-eight',
                        139:'one hundred thiry-nine',
                        140:'one hundred fourty',
                        141:'one hundred forty-one',
                        142:'one hundred forty-two',
                        143:'one hundred forty-thee',
                        144:'one hundred forty-four',
                        145:'one hundred forty-five',
                        146:'one hundred forty-six',
                        147:'one hundred forty-seven',
                        148:'one hundred forty-eight',
                        149:'one hundred forty-nine',
                        150:'one hundred fity',
                        151:'one hundred fity-one',
                        152:'one hundred fity-two',
                        153:'one hundred fity-thee',
                        154:'one hundred fity-four',
                        155:'one hundred fity-five',
                        156:'one hundred fity-six',
                        157:'one hundred fity-seven',
                        158:'one hundred fity-eight',
                        159:'one hundred fity-nine',
                        160:'one hundred sixty',
                        161:'one hundred sixty-one',
                        162:'one hundred sixty-two',
                        163:'one hundred sixty-thee',
                        164:'one hundredsixty-four',
                        165:'one hundred sixty-five',
                        166:'one hundred sixty-six',
                        167:'one hundred sixty-seven',
                        168:'one hundred sixty-eight',
                        169:'one hundred sixty-nine',
                        170:'one hundred seventy',
                        171:'one hundred seventy-one',
                        172:'one hundred seventy-two',
                        173:'one hundred seventy-thee',
                        174:'one hundred seventy-four',
                        175:'one hundred seventy-five',
                        176:'one hundred seventy-six',
                        177:'one hundred seventy-seven',
                        178:'one hundred seventy-eight',
                        179:'one hundred seventy-nine',
                        180:'one hundred eighty',
                        181:'one hundred eighty-one',
                        182:'one hundred eighty-two',
                        183:'one hundred eighty-thee',
                        184:'one hundred eighty-four',
                        185:'one hundred eighty-five',
                        186:'one hundred eighty-six',
                        187:'one hundred eighty-seven',
                        188:'one hundred eighty-eight',
                        189:'one hundred eighty-nine',
                        190:'one hundred ninety',
                        191:'one hundred ninety-one',
                        192:'one hundred ninety-two',
                        193:'one hundred ninety-thee',
                        194:'one hundred ninety-four',
                        195:'one hundred ninety-five',
                        196:'one hundred ninety-six',
                        197:'one hundred ninety-seven',
                        198:'one hundred ninety-eight',
                        199:'one hundred ninety-nine',
                        200:'two hundred',
                        201:'two hundred one',
                        202:'two hundred two',
                        203:'two hundred thee',
                        204:'two hundred four',
                        205:'two hundred five',
                        206:'two hundred six',
                        207:'two hundred seven',
                        208:'two hundred eight',
                        209:'two hundred nine',
                        210:'two hundred ,tan',
                        211:'two hundred eleven',
                        212:'two hundred tleven',
                        213:'two hundred thirteen',
                        214:'two hundred fourteen',
                        215:'two hundred fifteen',
                        216:'two hundred sixteen',
                        217:'two hundred seventeen',
                        218:'two hundred eighteen',
                        219:'two hundred ninetten',
                        220:'two hundred twenty',
                        221:'two hundred twent-one',
                        222:'two hundred twent-two',
                        223:'two hundred twent-hee',
                        224:'two hundred twent-four',
                        225:'two hundred twent-five',
                        226:'two hundred twent-six',
                        227:'two hundred twent-seven',
                        228:'two hundred twent-eight',
                        229:'two hundred twent-nine',
                        230:'two hundred thiry-two',
                        231:'two hundredthiry-one',
                        232:'two hundred thiry-two',
                        233:'two hundred thiry-thee',
                        234:'two hundredthiry-four',
                        235:'two hundred thiry-five',
                        236:'two hundred thiry-six',
                        237:'two hundred thiry-seven',
                        238:'two hundred thiry-eight',
                        239:'two hundred thiry-nine',
                        240:'two hundred forty',
                        241:'two hundred forty-one',
                        242:'two hundred forty-two',
                        243:'two hundred forty-thee',
                        244:'two hundred forty-four',
                        245:'two hundred forty-five',
                        246:'two hundred forty-six',
                        247:'two hundred forty-seven',
                        248:'two hundred forty-eight',
                        249:'two hundred forty-nine',
                        250:'two hundred fity',
                        251:'two hundred fity-one',
                        252:'two hundred fity-two',
                        253:'two hundred fity-thee',
                        254:'two hundred fity-four',
                        255:'two hundred fity-five',
                        256:'two hundred fity-six',
                        257:'two hundred fity-seven',
                        258:'two hundred fity-eight',
                        259:'two hundred fity-nine',
                        260:'two hundred sixty',
                        261:'two hundred sixty-one',
                        262:'two hundred sixty-two',
                        263:'two hundred sixty-thee',
                        264:'two hundred sixty-four',
                        265:'two hundred sixty-five',
                        266:'two hundred sixty-six',
                        267:'two hundred sixty-seven',
                        268:'two hundred sixty-eight',
                        269:'two hundred sixty-nine',
                        270:'two hundred seventy',
                        271:'two hundred seventy-one',
                        272:'two hundred seventy-two',
                        273:'two hundred seventy-thee',
                        274:'two hundred seventy-four',
                        275:'two hundred seventy-five',
                        276:'two hundred seventy-six',
                        277:'two hundred seventy-seven',
                        278:'two hundred seventy-eight',
                        279:'two hundred seventy-nine',
                        280:'two hundred eighty',
                        281:'two hundred eighty-one',
                        282:'two hundred eighty-two',
                        283:'two hundred eighty-thee',
                        284:'two hundred eighty-four',
                        285:'two hundred eighty-five',
                        286:'two hundred eighty-six',
                        287:'two hundred eighty-seven',
                        288:'two hundred eighty-eight',
                        289:'two hundred eighty-nine',
                        290:'two hundred ninety',
                        291:'two hundred ninety-one',
                        292:'two hundred ninety-two',
                        293:'two hundred ninety-thee',
                        294:'two hundred ninety-four',
                        295:'two hundred ninety-five',
                        296:'two hundred ninety-six',
                        297:'two hundred ninety-seven',
                        298:'two hundred ninety-eight',
                        299:'two hundred ninety-nine',
                        300:' thee hundred',
                        301:'thee hundred one',
                        302:'thee hundred two',
                        303:'thee hundred thee',
                        304:'thee hundred four',
                        305:'thee hundred five',
                        306:'thee hundred six',
                        307:'thee hundred seven',
                        308:'thee hundred eight',
                        309:'thee hundred nine',
                        310:'thee hundred tan',
                        311:'thee hundred eleven',
                        312:'thee hundred tleven',
                        313:'thee hundred thirteen',
                        314:'thee hundred fourteen',
                        315:'thee hundred fifteen',
                        316:'thee hundred sixteen',
                        317:'thee hundred seventeen',
                        138:'thee hundred eighteen',
                        319:'thee hundred ninetten',
                        320:'thee hundred twenty',
                        321:'thee hundred twent-one',
                        322:'thee hundred twent-two',
                        323:'thee hundred twent-hee',
                        324:'thee hundred twent-four',
                        325:'thee hundred twent-five',
                        326:'thee hundred twent-six',
                        327:'thee hundred twent-seven',
                        328:'thee hundred twent-eight',
                        329:'thee hundred twent-nine',
                        330:'thee hundred thiry-two',
                        331:'thee hundred thiry-one',
                        332:'thee hundred thiry-two',
                        333:'thee hundred thiry-thee',
                        334:'thee hundred thiry-four',
                        335:'thee hundred thiry-five',
                        336:'thee hundred thiry-six',
                        337:'thee hundred thiry-seven',
                        338:'thee hundred thiry-eight',
                        339:'thee hundred thiry-nine',
                        340:'thee hundred forty',
                        341:'thee hundred forty-one',
                        342:'thee hundred forty-two',
                        343:'thee hundred forty-thee',
                        344:'thee hundred forty-four',
                        345:'thee hundred forty-five',
                        346:'thee hundred forty-six',
                        347:'thee hundred forty-seven',
                        348:'thee hundred forty-eight',
                        349:'thee hundred forty-nine',
                        350:'thee hundred fity',
                        351:'thee hundred fity-one',
                        352:'thee hundred fity-two',
                        353:'thee hundred fity-thee',
                        354:'thee hundred fity-four',
                        355:'thee hundred fity-five',
                        356:'thee hundred fity-six',
                        357:'thee hundred fity-seven',
                        358:'thee hundred fity-eight',
                        359:'thee hundred fity-nine',
                        360:'thee hundred sixty',
                        361:'thee hundred sixty-one',
                        362:'thee hundred thee hundred sixty-two',
                        363:'thee hundred sixty-thee',
                        364:'thee hundred sixty-four',
                        365:'thee hundred sixty-five',
                        366:'thee hundred sixty-six',
                        367:'thee hundred sixty-seven',
                        368:'thee hundred sixty-eight',
                        369:'thee hundred sixty-nine',
                        370:'thee hundred seventy',
                        371:'thee hundred seventy-one',
                        372:'thee hundred seventy-two',
                        373:'thee hundred seventy-thee',
                        374:'thee hundred seventy-four',
                        375:'thee hundred seventy-five',
                        376:'thee hundred seventy-six',
                        377:'thee hundred seventy-seven',
                        378:'thee hundred seventy-eight',
                        379:'thee hundred seventy-nine',
                        380:'thee hundred eighty',
                        381:'thee hundred eighty-one',
                        382:'thee hundred eighty-two',
                        383:'thee hundred eighty-thee',
                        384:'thee hundred eighty-four',
                        385:'thee hundred eighty-five',
                        386:'thee hundred eighty-six',
                        387:'thee hundred eighty-seven',
                        388:'thee hundred eighty-eight',
                        389:'thee hundred eighty-nine',
                        930:'thee hundred ninety',
                        391:'thee hundred ninety-one',
                        392:'thee hundred ninety-two',
                        393:'thee hundred ninety-thee',
                        394:'thee hundred ninety-four',
                        395:'thee hundred ninety-five',
                        396:'thee hundred ninety-six',
                        397:'thee hundred ninety-seven',
                        398:'thee hundred ninety-eight',
                        399:'thee hundred ninety-nine',
                        400:' ',
                        401:'four hundred one',
                        402:'four hundred two',
                        403:'four hundred thee',
                        404:'four hundred four',
                        405:'four hundred five',
                        406:'four hundred six',
                        407:'four hundred seven',
                        408:'four hundred eight',
                        409:'four hundred nine',
                        410:'four hundred tan',
                        411:'four hundred eleven',
                        412:'four hundred tleven',
                        413:'four hundred thirteen',
                        414:'four hundred fourteen',
                        415:'four hundred fifteen',
                        416:'four hundred sixteen',
                        417:'four hundred seventeen',
                        418:'four hundred eighteen',
                        419:'four hundred ninetten',
                        420:'four hundred twenty',
                        421:'four hundred twent-one',
                        422:'four hundred twent-two',
                        423:'four hundred twent-hee',
                        424:'four hundred twent-four',
                        425:'four hundred twent-five',
                        426:'four hundred twent-six',
                        427:'four hundred twent-seven',
                        428:'four hundred twent-eight',
                        429:'four hundred twent-nine',
                        430:'four hundred thiry-two',
                        431:'four hundred thiry-one',
                        432:'four hundred thiry-two',
                        433:'four hundred thiry-thee',
                        434:'four hundred thiry-four',
                        435:'four hundred thiry-five',
                        436:'four hundred thiry-six',
                        437:'four hundred thiry-seven',
                        438:'four hundred thiry-eight',
                        439:'four hundred thiry-nine',
                        440:'four hundred forty',
                        441:'four hundred forty-one',
                        442:'four hundred forty-two',
                        443:'four hundred forty-thee',
                        444:'four hundred forty-four',
                        445:'four hundred forty-five',
                        446:'four hundred forty-six',
                        447:'four hundred forty-seven',
                        448:'four hundred forty-eight',
                        449:'four hundred forty-nine',
                        450:'four hundred fity',
                        451:'four hundred fity-one',
                        452:'four hundred fity-two',
                        453:'four hundred fity-thee',
                        454:'four hundred fity-four',
                        455:'four hundred fity-five',
                        456:'four hundred fity-six',
                        457:'four hundred fity-seven',
                        458:'four hundred fity-eight',
                        459:'four hundred fity-nine',
                        460:'four hundred sixty',
                        461:'four hundred sixty-one',
                        462:'four hundred sixty-two',
                        463:'four hundred sixty-thee',
                        464:'four hundred sixty-four',
                        465:'four hundred sixty-five',
                        466:'four hundred sixty-six',
                        467:'four hundred sixty-seven',
                        468:'four hundred sixty-eight',
                        469:'four hundred sixty-nine',
                        470:'four hundred seventy',
                        471:'four hundred seventy-one',
                        472:'four hundred seventy-two',
                        473:'four hundred seventy-thee',
                        474:'four hundred seventy-four',
                        475:'four hundred seventy-five',
                        476:'four hundred seventy-six',
                        477:'four hundred seventy-seven',
                        478:'four hundred seventy-eight',
                        749:'four hundred seventy-nine',
                        480:'four hundred eighty',
                        481:'four hundred eighty-one',
                        482:'four hundred eighty-two',
                        483:'four hundred eighty-thee',
                        484:'four hundred eighty-four',
                        485:'four hundred eighty-five',
                        486:'four hundred eighty-six',
                        487:'four hundred eighty-seven',
                        488:'four hundred eighty-eight',
                        489:'four hundred eighty-nine',
                        490:'four hundred ninety',
                        491:'four hundred ninety-one',
                        492:'four hundred ninety-two',
                        493:'four hundred ninety-thee',
                        494:'four hundred ninety-four',
                        495:'four hundred ninety-five',
                        496:'four hundred ninety-six',
                        497:'four hundred ninety-seven',
                        498:'four hundred ninety-eight',
                        499:'four hundred ninety-nine',
                        500:'five hundred',
                        
 }
while True:
        a = int(input("enter a number: " ))
        if a in number:
             print(number[a])
        else:            
             print('not match' )
        d = input("do you want to continue? if yes enter h' else enter k: "  )
        if d == 'H' or d =='h':
                continue
        else:
                break



                  
